USE [master]
GO

/****** Object:  Database [Diabetes_Helper]    Script Date: 2019-11-23 8:28:08 AM ******/
CREATE DATABASE [Diabetes_Helper]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Diabetes_Helper', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Diabetes_Helper.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Diabetes_Helper_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Diabetes_Helper_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Diabetes_Helper] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Diabetes_Helper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Diabetes_Helper] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET ARITHABORT OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Diabetes_Helper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Diabetes_Helper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Diabetes_Helper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Diabetes_Helper] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Diabetes_Helper] SET  MULTI_USER 
GO

ALTER DATABASE [Diabetes_Helper] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Diabetes_Helper] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Diabetes_Helper] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Diabetes_Helper] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Diabetes_Helper] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Diabetes_Helper] SET QUERY_STORE = OFF
GO

USE [Diabetes_Helper]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Diabetes_Helper] SET  READ_WRITE 
GO


